### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [vneogi199/Classification-of-Fruit-images-using-VGG16#1]
Hi,

When I tried to run yours code, I get an error message this line => 
**"result = np.round(model.predict_generator(valid_generator))"**
error message is: ValueError: `steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `steps` or use the `keras.utils.Sequence` class.

How can solve this problem? I dont know, how can I choose true step size.(parameter of predict_generator) Please help.

Note: I can try this code:
result = np.round(model.predict_generator(valid_generator, steps=len(valid_generator)))
It's work but results are bad. All predictions are incorrect.

**Comment by vneogi199** [comment]
Seems like an issue with Keras that is fixed now [https://github.com/keras-team/keras/issues/11445](https://github.com/keras-team/keras/issues/11445)

**Comment by ghost** [comment]
Okey, I will try again, I hope solve it.

thank you,
